spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sandbox;MODE=PostgreSQL;
    username: sandman
    password: abc
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
    type:
      descriptor:
        sql:
          BasicBinder: trace
